name: Deploy web app to Azure Static Web Apps
env:
  APP_LOCATION: "automotive-maintenance-pro"
  API_LOCATION: "api"
  OUTPUT_LOCATION: ".next"
  NODE_VERSION: "18.x"

on:
  push:
    branches:
      - azure-static-web-app
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install Dependencies
        working-directory: ${{ env.APP_LOCATION }}
        run: npm install
        
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}